### PR TITLE
fix(TypeScript): add `grid` and `gridTemplate` 

### LINKED ISSUE #402: Typings `grid` property missed
```
"glamor": "2.20.40",
"glamorous": "4.12.1",
"react": "16.2.0",
"typescript": "2.7.1"
```
Prop `grid` is not isset in typings
screen shot 2018-03-27 at 14 21 22

### PR DESCRIPTION
**Pull request by whtsky**
**What**:
fix #402

**Why**:
N/A

**How**:
https://developer.mozilla.org/en-US/docs/Web/CSS/grid
https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template

**Checklist**:

* [x] Documentation
* [x] Tests
* [x] Ready to be merged 
* [x] Added myself to contributors table

### CODE REVIEW

File: typings/css-properties.d.ts [hunk 1]
```diff
@@ -931,6 +936,11 @@ export interface CSSPropertiesCompleteSingle {
 
   gridRowSpan?: CSSWideKeyword | number
 
+  /**
+   * Shorthand property that sets the grid-template-rows, grid-template-columns, and grid-template-areas.
+   */
+  gridTemplate?: CSSWideKeyword | string | 'none'
```
Comment (Ailrun) [inline typings/css-properties.d.ts]: `string | 'none'` is just a `string` type. Please remove `'none'`.

**Comment by kentcdodds** [comment]
Thanks!
