### PR TITLE
fix(typescript): complete glamorous component factories

### LINKED ISSUE #212: Typescript: Glamorous Component Factory is not as strict as intended
- `glamorous` version: 3.23.5

Problem description:

Currently there are a number ways to use glamorous with typescript where you have incomplete typesafety.

We've started coming across these with a number of our components and internal glamorous helpers.

Suggested solution:

Improve/fix the typings and add a test file for things that should fail with typescript.

I've got a WIP pr at the following link, I'm just waiting on an issue I've raised on the typescript repo before finishing this off.

https://github.com/luke-john/glamorous/pull/1

I may not get a chance to do that for a few days so opening this issue in the meantime in case anyone else hits up against this.

### PR DESCRIPTION
**Pull request by luke-john**
**What and Why**:

This pr follows on from the work in #214  and the discussion on that pr.

BREAKING CHANGE:

These typings use language features of typescript 2.4+.

This fixes a number of issues with the glamorous component factory
typings

* style objects can only be sets of css or svg properties
* style functions can return a string classname or style object
* glamorous arguments can be a string classname
* glamorous arguments can be a StyleArray containing classnames, style objects and style functions.

This also improves the developer experience provided by intellisense                     
with autocomplete once again working.

This closes #212

This also updates the typing for theme to match the new behaviour which landed in #207.

**How**:

Updated the type definitions and the related tests.

**Checklist**:
- [x] Documentation
- [x] Tests
- [x] Ready to be merged
- [ ] Added myself to contributors table N/A

These updated typings still have Theme as a seperate parameter to the glamorous component factory function arguments.  I'll try and update this in a seperate pr sometime in the next few days.

I've also taken liberty in the naming of the following argument types as I was unable to find any language describing them in the glamorous documentation.

StyleObject, StyleFunction, StyleFunctionArray, StyleArray

I'd be happy to update these types if someone has suggestions for better names.

### CODE REVIEW

**Comment by luke-john** [comment]
Ahh, looks like I've mistakenly brought in some commits from master.

Likely won't get a chance to fix this today unfortunately.

**Comment by luke-john** [comment]
See below for screenshots of improvement to intellisense.

image

image

Unfortunately the union means that when a style function returns something that is not a valid styles set, it gives hints about the array return type rather than the valid css properties.  However it still gives the correct key, so upon removing the invalid type you will get hinting. See below for example.

image

File: typings/component-factory.ts [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+    | Partial<Properties>
+    | string
+    | StyleFunction<Properties, Props, Theme>
+  >
+}
+
+export type StyleArray<Properties, Props, Theme> = Array<
+  | StyleFunctionArray<Properties, Props, Theme>
+  | string
+  | Partial<Properties>
```
Comment (luke-john) [inline typings/component-factory.ts]: I'm pretty sure this can also take a StyleFunction

File: typings/component-factory.ts [hunk 2]
```diff
@@ -0,0 +1,45 @@
+import { GlamorousComponent } from './glamorous-component'
+/**
+ * StyleObject is an objects of Style Properties.
+ *
+ * @see {@link https://github.com/paypal/glamorous/blob/master/src/create-glamorous.js#L28-L131}
+ */
+export type StyleObject<Styles> = Partial<Styles>
```
Comment (luke-john) [inline typings/component-factory.ts]: this is not currently being used below and should probably be removed

File: typings/glamorous.d.ts [hunk 3]
```diff
@@ -62,7 +76,7 @@ export function withTheme<ExternalProps, Theme>(
   component: React.ComponentClass<ExternalProps & { theme: Theme }>
 ): React.ComponentClass<ExternalProps>
 
-export function withTheme<ExternalProps, Theme>(
+  export function withTheme<ExternalProps, Theme>(
```
Comment (luke-john) [inline typings/glamorous.d.ts]: Should investigate using Omit to make this easier similar to styled-components. 

https://github.com/styled-components/styled-components/pull/982/files

File: typings/glamorous.d.ts [hunk 4]
```diff
@@ -36,18 +50,18 @@ export interface Config {
...
-    options?: GlamorousOptions,
-  ): StyledFunction<Props, CSSProperties>
+    options?: Partial<GlamorousOptions>,
+  ): GlamorousComponentFactory<Props, CSSProperties>
   <Props>(
     component:Component<Props>,
-    options?: GlamorousOptions,
-  ): StyledFunction<Props, SVGProperties>
+    options?: Partial<GlamorousOptions>,
+  ): GlamorousComponentFactory<Props, SVGProperties>
```
Comment (luke-john) [inline typings/glamorous.d.ts]: should also add support for all the html/svg tags https://github.com/wooorm/html-tag-names/blob/master/index.json and https://github.com/wooorm/svg-tag-names/blob/master/index.json

**Comment by kentcdodds** [comment]
How's this going? Would love to get this merged soon because I want to release it with the next major version

**Comment by luke-john** [comment]
Whilst I tried to add a bunch of new tests around all the new features, I was hoping to land this at work to test it as well given the significant amount of glamorous code we have now :).

Unfortunately this was held up with upgrading to typescript 2.4.2, that landed Friday so I'll hopefully be able to land this tomorrow.

I'll also finish writing some upgrade notes for typescript tonight.  Was there any plan to publish upgrading notes currently? If so I'll try and follow the same format, and it would be great if a link to the typescript upgrade notes was included.

**Comment by kentcdodds** [comment]
Definitely. We'll just include the upgrade notes as party of the GitHub release notes. I think you should be able to update that yourself. Or you can provide that in a comment here and I'll copy it in 👍

**Comment by kentcdodds** [comment]
Let me know when this is ready to merge 😀

**Comment by luke-john** [comment]
Landed on our code base today and discovered a couple of issues which should now be fixed :).

Will also get some of our devs to do pr tomorrow morning if @sammkj or @ErikCupal aren't available to review.

**Comment by ErikCupal** [comment]
@luke-john sorry, was busy and didn't have time to look at such a big PR :D. I'll review it now.

File: other/TYPESCRIPT_USAGE.md [hunk 5]
```diff
@@ -10,22 +10,45 @@ Pull requests to improve them are welcome and appreciated. If you've never contr
...
+### glamorousComponentFactory
 
-To use dynamic styles with custom props use generics. Example:
+The typings for
+* creating your own glamorous component factories
+* using built-in glamorous component factories
+are complete.
+
+```
+// Creating your own
```
Comment (ErikCupal) [inline other/TYPESCRIPT_USAGE.md]: swap for ```ts for better colors ;)

File: other/TYPESCRIPT_USAGE.md [hunk 6]
```diff
@@ -10,22 +10,45 @@ Pull requests to improve them are welcome and appreciated. If you've never contr
...
+}
+
+const MyStyledDiv = glamorous.div<Props>(
   {
     margin: 1,
   },
-  props => ({
-    padding: props.noPadding ? 0 : 4,
+  ({noPadding, theme}) => ({
+    padding: noPadding ? 0 : 4,
```
Comment (ErikCupal) [inline other/TYPESCRIPT_USAGE.md]: Would be nicer (though not necessary) if the code style would be consistent here :). I mean
```ts
({ noPadding, theme }) => ({
```
instead of
```ts
({noPadding, theme}) => ({
```
the same for this
```ts
<ThemeProvider theme={{color: 'red'}}>
```

File: test/glamorous.test.tsx [hunk 7]
```diff
@@ -5,48 +5,102 @@ import glamorous, { withTheme, ThemeProvider } from "../";
...
+const Divider = glamorous.span<{
+  theme: { main: { color: string; } }
+}>(
   {
     "fontSize": "10px",
     "zIndex": "auto"
   },
-  (props, theme) => ({
-    "color": theme && theme.main.color,
+  ({theme}) => ({
```
Comment (ErikCupal) [inline test/glamorous.test.tsx]:
````ts
({ theme }) => ({
```
would be better :). The same thing on other lines below

**Comment by kentcdodds** [comment]
Thank you so much for all your work on this project!

Do you think you could make me a little burb (and maybe a gif) that I could include in the release notes as well as the blogpost when we release the next major version? That'd be great :)

File: other/TYPESCRIPT_USAGE.md (hunk 6 above)
Comment (luke-john) [inline other/TYPESCRIPT_USAGE.md]: I've still got an open issue for fixing tslint, will make sure this is addressed when that get's picked up. 

big fan of keeping things consitant 👍

**Comment by luke-john** [comment]
@ErikCupal yeah I realise this PR had become fairly large, so thanks for taking the time to give it review :)

@kentcdodds thanks for making the project, it's been awesome using it at work and on personal projects.

A burb should be fine, I'd intended to already do one but got held up. I'll also have a look at doing a gif but I'm not familiar with any tools for that, do you have any suggestions?

**Comment by kentcdodds** [comment]
> I'll also have a look at doing a gif but I'm not familiar with any tools for that, do you have any suggestions?

[LICEcap](https://www.cockos.com/licecap/) is great :+1:

Thanks again!

**Comment by luke-john** [comment]
@kentcdodds see below for a summary of the type updates 

## Upgrading with Typescript

The typescript support for glamorous is now nearing completion with all component factory arguments shapes usable.  As part of providing this support the return type of glamorous function arguments have been corrected, so you may discover errors when upgrading.

To see what's now supported out of the box check out the [Typescript Usage Notes](https://github.com/paypal/glamorous/blob/master/other/TYPESCRIPT_USAGE.md).

The typings for vnext have the theme passed through via props, so you simply need to add it to your component factories Props interface.  The typings take care of omitting the theme from the returned Glamorous Component.

```ts
interface Props {
    visible: true
    theme: { color: 'red' }
}

const StyledComponent = glamorous.div<Props>(
    ({ visible, theme }) => ({

    })
)
```

Also if you've been making use of any of the internal types, there's been some name changes to align the typing with the documentation.

* `HTMLGlamorousInterface` -> `HTMLComponentFactory`,
* `StyledFunction` -> `GlamorousComponentFactory`,
* `SVGGlamorousInterface` -> `SVGComponentFactory`

The typings take advantage of language features so you'll need to be on or above typescript 2.4.1.

### Demo

example_typescript_usage

**Comment by kentcdodds** [comment]
@luke-john, I noticed in this gif you keep using the mouse to click away and then click back again. I'm guessing this is to make the popover go away. Do you do this in your normal workflow? It looks a little bad :-/ Could you just make a gif of your normal workflow?

**Comment by kentcdodds** [comment]
I just edited it in screenflow. Let me know what you think:

screenflow

**Comment by kentcdodds** [comment]
Oh snap. I just realized that screenflow cut it short :-(

Yeah, if you could record another version that would be awesome :)

**Comment by luke-john** [comment]
I have parameter hints turned off in vscode as they are often annoying like that, though you can just hit escape to dismiss them.

Have redone

typescript-screencap

**Comment by kentcdodds** [comment]
Very cool! Looks great :+1:
